### ISSUE TITLE
Auth response 400

### ISSUE THREAD

**Issue by domodial** [olf/dashing_netatmo#1]
Hello,
I have installed the widget on rapsberry PI.
Dashing work fine.

But, I don't see Netatmo value on the widget.

Terminal say Auth Netatmo response: 400
My ID Key, app_secret, username and password are Ok, I don't understand.

I don't have yaml installed.

Sorry I'm a noob with raspbian/lunix/and others.

an idea ?

**Comment by domodial** [comment]
I don't have response 400 now.
I have intalled Yaml but the widget do not work...
Please help me. Thanks

**Comment by olf** [comment]
Do you have any other error message from dashing?

**Comment by domodial** [comment]
no error in the terminal, no error on the dashing, and if I look in my
Netatmo application, I see that the app request is accepted. Communication
is good but there is no back up information on dashing into the box.

Le mer. 9 mars 2016 à 11:46, Olaf Peters notifications@github.com a
écrit :

**Comment by olf** [comment]
How did you configure the respective widget in the dashboard that you're displaying (in the dashboard/ directory of dashing)? 

See https://github.com/olf/raspiboard/blob/master/dashboards/raspi.erb for some examples.

Maybe the HTML example here in the README is not quite up to date.

**Comment by domodial** [comment]
Hello,

See the picture please, no error.

[image: Capture d’écran 2016-03-09 à 19.27.22.png]

Le mer. 9 mars 2016 à 11:46, Olaf Peters notifications@github.com a
écrit :

**Comment by domodial** [comment]
Indeed, I tested these possibilities by browsing your work, so I tested
these lines but I separate box with no values inside.

this is incredible...

Le mer. 9 mars 2016 à 17:24, Olaf Peters notifications@github.com a
écrit :

**Comment by olf** [comment]
The picture didn't get through. Can you upload the file from dashboards/ that you're using? I can try to reproduce it in my setup then.

Please do the uploads on GitHub, don't send them through email, they won't appear here in the issue.

**Comment by domodial** [comment]
This is my lines code into my xxx.erb

   <li data-row="3" data-col="1" data-sizex="1" data-sizey="2">
    <div data-id="netatmo" data-view="Netatmo"></div>
  </li>

Le mer. 9 mars 2016 à 20:02, Olaf Peters notifications@github.com a
écrit :

**Comment by domodial** [comment]
here the config file

This is fake app_id and app_secret

app_id: 56dee4ce545487dfdfd5f4d5eab
app_secret: 7ZQdQ7stzEyrHexjhbskekalsMRhgSGb4B4aZH3p
username: my@gmail.com
password: Mypass
indoor_name: Module_interieur
outdoor_name: Module_exterieur
interval: 60s

Le mer. 9 mars 2016 à 20:02, Olaf Peters <notifications@github.com> a
écrit :

**Comment by domodial** [comment]
[image: Capture d’écran 2016-03-09 à 20.24.05.png]
this is capture of Netatmo website.
The Dashboard PI Bernie is OK for Auth.

Le mer. 9 mars 2016 à 20:02, Olaf Peters notifications@github.com a
écrit :

**Comment by domodial** [comment]
![capture d ecran 2016-03-09 a 19 27 22](https://cloud.githubusercontent.com/assets/17140104/13647691/8878ee94-e635-11e5-8186-96471cc1df25.png)

**Comment by domodial** [comment]
![capture d ecran 2016-03-09 a 20 24 05](https://cloud.githubusercontent.com/assets/17140104/13647706/96aef350-e635-11e5-8f5a-17cd7fcdff64.png)

**Comment by olf** [comment]
Are you sure that you have the right names configured for indoor_name and outdoor_name in netatmo.yml?

Please check on the NetAtmo site, in settings:

![settings](https://cloud.githubusercontent.com/assets/380572/13647936/a09f1736-e636-11e5-9585-c920e0b08278.png)

You need to put these two names for indoor_name and outdoor_name:

![names](https://cloud.githubusercontent.com/assets/380572/13647862/5605d91c-e636-11e5-8791-923d7a6e24d2.png)

Those screenshots are from my configuration, and these are the corresponding lines from netatmo.yml:

indoor_name: Home
outdoor_name: Outdoor

**Comment by domodial** [comment]
I had written the name of the indoor unit and outdoor as shown in config.

And you say that's the name of the station and the outdoor unit !
And now it works perfectly! Thank you for that clarification.

Maybe the name of the indoor function is to change? because there is confusion I think. Or I did not understand anything :) Thanks for a great widget !

Befor
![capture d ecran 2016-03-10 a 07 19 54](https://cloud.githubusercontent.com/assets/17140104/13661209/fbad86bc-e690-11e5-8614-d698839f7fc1.png)

After
![capture d ecran 2016-03-10 a 07 13 02](https://cloud.githubusercontent.com/assets/17140104/13661214/058dc214-e691-11e5-9ecc-b7474b977f5b.png)

**Comment by olf** [comment]
I'm glad that it works for you now. :smile:
